input {
  # Point the ASA "logging host" at these ports.
  udp {
    id   => "cisco_asa_udp"
    port => "${ASA_UDP_PORT:5514}"
  }
  tcp {
    id   => "cisco_asa_tcp"
    port => "${ASA_TCP_PORT:5514}"
  }
}
