output {
  elasticsearch {
    id                          => "es_cisco_asa"
    hosts                       => ["${ES_HOSTS}"]
    api_key                     => "${ES_API_KEY}"
    ssl_certificate_authorities => ["${ES_CA_CERT:/usr/share/logstash/config/certs/ca.crt}"]

    # Writes to the logs-cisco.asa-<namespace> data stream.
    data_stream           => "true"
    data_stream_type      => "logs"
    data_stream_dataset   => "cisco.asa"
    data_stream_namespace => "${DS_NAMESPACE:default}"
  }
}
