apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic
spec:
  version: 9.5.0
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  kibanaRef:
    name: kibana
  elasticsearchRefs:
    - name: elasticsearch
  deployment:
    replicas: 2
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
